### ISSUE TITLE
Using rating for anonymous users

### ISSUE THREAD

**Issue by Photoshopper** [AbdullahGhanem/rating#10]
I should send a $user instance for rating() method, but what in a case of anonymous users? The only solution that I see, it's to create an anonymous user and use it when the user is not logged in.

Is there another way?

**Comment by AbdullahGhanem** [comment]
yes, you can use this  anonymous users

```
//use this line in controller
use Ghanem\Rating\Models\Rating;
```

```
$comment = App\Comment::first();

Rating::create([
    'rating' => 5,
    'author_id'  => 1,
    'author_type'  => 'anonymous',
    'ratingable_id' => $comment->id,
    'ratingable_type' => 'App\Comment',
]);
dd($comment->sumRating)
```
