### ISSUE TITLE
Lavarel 5.3 - Publishing complete for tag []!

### ISSUE THREAD

**Issue by mozartvn** [AbdullahGhanem/rating#14]
hi 

I use Rating with lavarel 5.3.
I run the following command : 

```
php artisan config:clear
php artisan vendor:publish --provider="Ghanem\Rating\RatingServiceProvider"
```
but I catch this issues : 
```

m@ubuntu:~/lavarel/app$ php artisan vendor:publish --provider="Ghanem\Rating\RatingServiceProvider"
Nothing to publish for tag [].
```
Does Rating support Lavarel 5.3 ?

Thanks.

**Comment by ghost** [comment]
Hi @mozartvn, yes the package work with 5.* :100: 

Use the following command:
`php artisan rating:migration`

And use in your model:
```php
<?php

namespace App;

use Ghanem\Rating\Traits\Ratingable as Rating;
use Illuminate\Database\Eloquent\Model;

class Post extends Model implements Rating
{
    use Rating;
}
```

**Comment by mozartvn** [comment]
`https://github.com/AbdullahGhanem/rating/blob/master/src/Traits/Ratingable.php`

Ratingable is Trait, how could you implement it like Interface ?

I have made it work.

```
<?php

namespace App;

use Ghanem\Rating\Contracts\Rating;
use Ghanem\Rating\Traits\Ratingable as RatingTrait;
use Illuminate\Database\Eloquent\Model;

class Post extends Model implements Rating
{
    use RatingTrait;
}
```


https://github.com/mozartvn/rating

Regards !

**Comment by ghost** [comment]
Hi, @mozartvn changes have already been made. Look at my last pull request.
