### ISSUE TITLE
so confusing documentation

### ISSUE THREAD

**Issue by robertnicjoo** [AbdullahGhanem/rating#20]
I just installed this package, model is set, database are published, but how to show rating in my blade and how to collect it from users??

**Comment by Fatih90** [comment]
this package is just a fork of https://github.com/willvincent/laravel-rateable

this arab (terorist) just changed the file names

**Comment by AbdullahGhanem** [comment]
i don't fork this repo from [retable](https://github.com/willvincent/laravel-rateable)
@Fatih90 you can see the difference between my [repo tags](https://github.com/AbdullahGhanem/rating/tags) and MR will vincent's [repo tags](https://github.com/willvincent/laravel-rateable/tags),
and you called me arab (terorist), It is proud of me to be an Arab.

[Al-Khwarizmi](https://en.wikipedia.org/wiki/Muhammad_ibn_Musa_al-Khwarizmi) said about man:
If a man has a morality, he = 1
If it is beautiful, add zero to one = 10
If he has money, add another zero = 100
If he has a percentage, add another zero = 1000
If the number goes one, which is ethics, the value of the person has gone, and the zeros have remained worthless.

**Comment by Fatih90** [comment]
it is the same look at the difference
https://github.com/AbdullahGhanem/rating/blob/master/src/Commands/MigrationCommand.php

https://github.com/willvincent/laravel-rateable/blob/master/src/commands/MigrationCommand.php

all you did is changed some strings and paths
