### ISSUE TITLE
Error in Laravel 5.2

### ISSUE THREAD

**Issue by mediaceh** [AbdullahGhanem/rating#8]
I have error with method $post->ratingPercent() 

`Object of class Illuminate\Support\Collection could not be converted to int`
`in Ratingable.php line 50`

`$total = $ratings->selectRaw('SUM(rating) as total')->pluck('total');
return ($quantity * $max) > 0 ? $total / (($quantity * $max) / 100) : 0;`

I check docs for query builder.

For 5.0 Laravel 
https://laravel.com/api/5.1/Illuminate/Database/Query/Builder.html#method_pluck
"Pluck a single column's value from the first result of a query."

For 5.2 Laravel 
https://laravel.com/api/5.2/Illuminate/Database/Query/Builder.htmll#method_pluck
"Get an array with the values of a given column."

In laravel 5.1 Pluck is deprecated and it is an alias for the "value" method.
In laravel 5.2 we need use Value instead Pluck. 

If you need fix it  for laravel 5.2 - replace Pluck method on Value in /vendor/ghanem/rating/src/Traits/Ratingable.php on line 50 or add condition "if is array" for compatibility with older version.

**Comment by AbdullahGhanem** [comment]
Thanks @mediaceh

**Comment by AbdullahGhanem** [comment]
now it work on all laravel version
